name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.x'

    - name: Install dependencies
      run: |
        brew install swiftlint
        bundle install --path vendor/bundle
        bundle exec pod install --repo-update

    - name: Build and test
      run: |
        xcodebuild -workspace ALM\ APP\ Dem0.xcworkspace -scheme ALM\ APP\ Dem0 -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" clean test | xcpretty -c
